import type {
  ActivityItem,
  Company,
  Contact,
  Invoice,
  Milestone,
  Project,
  Task,
  Ticket,
  User,
} from "./types";

export const users: User[] = [
  {
    id: "u-admin",
    name: "Dillon Morgan",
    initials: "DM",
    role: "admin",
    email: "dillon@dillonmorgan.com",
  },
  {
    id: "u-pm",
    name: "M. Doyle",
    initials: "MD",
    role: "pm",
    email: "mdoyle@dillonmorgan.com",
  },
  {
    id: "u-staff",
    name: "J. Kim",
    initials: "JK",
    role: "staff",
    email: "jkim@dillonmorgan.com",
  },
  {
    id: "u-client",
    name: "Dana Kessler",
    initials: "DK",
    role: "client",
    email: "dana@cascadeventures.com",
    companyId: "c-cascade",
  },
];

export const companies: Company[] = [
  {
    id: "c-northridge",
    name: "Northridge Retail Group",
    initials: "NR",
    status: "Active",
    accountManager: "J. Alvarez",
    openProjects: 3,
    openTickets: 1,
    lastActivity: "Aug 5, 2026",
    industry: "Retail",
    billingTerms: "Net 30",
    portalContacts: 2,
  },
  {
    id: "c-harlow",
    name: "Harlow & Pine Law",
    initials: "HP",
    status: "Prospect",
    accountManager: "J. Alvarez",
    openProjects: 0,
    openTickets: 0,
    lastActivity: "Aug 1, 2026",
    industry: "Legal",
    billingTerms: "Net 15",
    portalContacts: 0,
  },
  {
    id: "c-oakton",
    name: "Oakton Technologies",
    initials: "OT",
    status: "Overdue Inv.",
    accountManager: "S. Cho",
    openProjects: 1,
    openTickets: 3,
    lastActivity: "Jul 29, 2026",
    industry: "Technology",
    billingTerms: "Net 30",
    portalContacts: 1,
  },
  {
    id: "c-cascade",
    name: "Cascade Ventures",
    initials: "CV",
    status: "Active",
    accountManager: "M. Doyle",
    openProjects: 5,
    openTickets: 1,
    lastActivity: "Aug 5, 2026",
    industry: "Manufacturing & Distribution",
    billingTerms: "Net 30",
    portalContacts: 3,
  },
  {
    id: "c-bellweather",
    name: "Bellweather Logistics",
    initials: "BL",
    status: "Active",
    accountManager: "S. Cho",
    openProjects: 2,
    openTickets: 0,
    lastActivity: "Aug 4, 2026",
    industry: "Logistics",
    billingTerms: "Net 30",
    portalContacts: 2,
  },
];

export const contacts: Contact[] = [
  {
    id: "ct-dana",
    name: "Dana Kessler",
    initials: "DK",
    companyId: "c-cascade",
    companyName: "Cascade Ventures",
    title: "VP Operations",
    email: "dana@cascadeventures.com",
    portal: "Enabled",
    lastInteraction: "Aug 5, 2026",
  },
  {
    id: "ct-ravi",
    name: "Ravi Thakur",
    initials: "RT",
    companyId: "c-cascade",
    companyName: "Cascade Ventures",
    title: "IT Director",
    email: "ravi@cascadeventures.com",
    portal: "Enabled",
    lastInteraction: "Aug 3, 2026",
  },
  {
    id: "ct-nina",
    name: "Nina Ortiz",
    initials: "NO",
    companyId: "c-northridge",
    companyName: "Northridge Retail Group",
    title: "Procurement Lead",
    email: "nina@northridge.com",
    portal: "Not Invited",
    lastInteraction: "Jul 28, 2026",
  },
];

export const projects: Project[] = [
  {
    id: "p-warehouse",
    name: "Q3 Warehouse Rollout",
    companyId: "c-cascade",
    companyName: "Cascade Ventures",
    manager: "M. Doyle",
    progress: 70,
    status: "On Track",
    due: "Aug 22, 2026",
    budgetHours: 420,
    loggedHours: 294,
    marginPct: 31,
    portalShared: true,
    portalContacts: 2,
  },
  {
    id: "p-website",
    name: "Website Replatform",
    companyId: "c-cascade",
    companyName: "Cascade Ventures",
    manager: "M. Doyle",
    progress: 35,
    status: "At Risk",
    due: "Sep 10, 2026",
    budgetHours: 180,
    loggedHours: 92,
    marginPct: 22,
    portalShared: true,
    portalContacts: 2,
  },
  {
    id: "p-vendor",
    name: "Vendor Onboarding Portal",
    companyId: "c-cascade",
    companyName: "Cascade Ventures",
    manager: "S. Cho",
    progress: 90,
    status: "On Track",
    due: "Aug 12, 2026",
    budgetHours: 120,
    loggedHours: 108,
    marginPct: 38,
    portalShared: true,
    portalContacts: 2,
  },
  {
    id: "p-fleet",
    name: "Fleet Tracking Pilot",
    companyId: "c-bellweather",
    companyName: "Bellweather Logistics",
    manager: "S. Cho",
    progress: 15,
    status: "Overdue",
    due: "Jul 30, 2026",
    budgetHours: 200,
    loggedHours: 55,
    marginPct: 18,
    portalShared: false,
    portalContacts: 0,
  },
  {
    id: "p-pos",
    name: "POS Integration",
    companyId: "c-northridge",
    companyName: "Northridge Retail Group",
    manager: "J. Alvarez",
    progress: 55,
    status: "On Track",
    due: "Aug 28, 2026",
    budgetHours: 160,
    loggedHours: 88,
    marginPct: 29,
    portalShared: true,
    portalContacts: 1,
  },
];

export const milestones: Milestone[] = [
  {
    id: "m1",
    projectId: "p-warehouse",
    name: "Site Survey Complete",
    due: "Jul 18",
    status: "Approved",
  },
  {
    id: "m2",
    projectId: "p-warehouse",
    name: "Racking Installation",
    due: "Aug 8",
    status: "In Progress",
  },
  {
    id: "m3",
    projectId: "p-warehouse",
    name: "WMS Go-Live",
    due: "Aug 22",
    status: "Not Started",
  },
  {
    id: "m4",
    projectId: "p-website",
    name: "Homepage Design Review",
    due: "Aug 9",
    status: "In Progress",
  },
  {
    id: "m5",
    projectId: "p-vendor",
    name: "Final Sign-off",
    due: "Aug 12",
    status: "Not Started",
  },
];

export const tickets: Ticket[] = [
  {
    id: "t-1042",
    number: 1042,
    subject: "Portal login issue",
    companyId: "c-cascade",
    companyName: "Cascade Ventures",
    priority: "Urgent",
    assignee: "J. Kim",
    slaDue: "2h 10m",
    status: "In Progress",
    submitted: "Aug 5, 2026",
  },
  {
    id: "t-1045",
    number: 1045,
    subject: "Invoice PDF missing line items",
    companyId: "c-oakton",
    companyName: "Oakton Technologies",
    priority: "High",
    assignee: "Unassigned",
    slaDue: "1d 4h",
    status: "Open",
    submitted: "Aug 4, 2026",
  },
  {
    id: "t-1038",
    number: 1038,
    subject: "Retainer hours clarification",
    companyId: "c-northridge",
    companyName: "Northridge Retail Group",
    priority: "Low",
    assignee: "M. Doyle",
    slaDue: "3d",
    status: "Resolved",
    submitted: "Jul 30, 2026",
  },
];

export const tasks: Task[] = [
  {
    id: "tk1",
    name: "Configure WMS user roles",
    projectId: "p-warehouse",
    projectName: "Q3 Warehouse Rollout",
    assignee: "J. Kim",
    assigneeInitials: "JK",
    status: "Not Started",
    clientEditable: false,
  },
  {
    id: "tk2",
    name: "Draft training materials",
    projectId: "p-warehouse",
    projectName: "Q3 Warehouse Rollout",
    assignee: "S. Ahmed",
    assigneeInitials: "SA",
    status: "Not Started",
    clientEditable: true,
  },
  {
    id: "tk3",
    name: "Vendor API credentials",
    projectId: "p-vendor",
    projectName: "Vendor Onboarding Portal",
    assignee: "S. Cho",
    assigneeInitials: "SC",
    status: "Not Started",
    clientEditable: false,
  },
  {
    id: "tk4",
    name: "Install racking Zone B",
    projectId: "p-warehouse",
    projectName: "Q3 Warehouse Rollout",
    assignee: "M. Doyle",
    assigneeInitials: "MD",
    status: "In Progress",
    dueLabel: "Due Tomorrow",
    clientEditable: false,
  },
  {
    id: "tk5",
    name: "QA fleet tracking sync",
    projectId: "p-fleet",
    projectName: "Fleet Tracking Pilot",
    assignee: "S. Cho",
    assigneeInitials: "SC",
    status: "In Progress",
    clientEditable: false,
  },
  {
    id: "tk6",
    name: "Client review homepage design",
    projectId: "p-website",
    projectName: "Website Replatform",
    assignee: "J. Kim",
    assigneeInitials: "JK",
    status: "Review",
    clientEditable: true,
  },
  {
    id: "tk7",
    name: "Site survey report",
    projectId: "p-warehouse",
    projectName: "Q3 Warehouse Rollout",
    assignee: "M. Doyle",
    assigneeInitials: "MD",
    status: "Done",
    dueLabel: "Completed Jul 18",
    clientEditable: false,
  },
  {
    id: "tk8",
    name: "Kickoff deck sent",
    projectId: "p-warehouse",
    projectName: "Q3 Warehouse Rollout",
    assignee: "S. Ahmed",
    assigneeInitials: "SA",
    status: "Done",
    dueLabel: "Completed Jul 10",
    clientEditable: false,
  },
];

export const invoices: Invoice[] = [
  {
    id: "inv-2291",
    number: "INV-2291",
    companyId: "c-cascade",
    companyName: "Cascade Ventures",
    amount: 12400,
    terms: "Net 30",
    due: "Aug 3, 2026",
    status: "Overdue",
  },
  {
    id: "inv-2298",
    number: "INV-2298",
    companyId: "c-northridge",
    companyName: "Northridge Retail Group",
    amount: 8900,
    terms: "Net 30",
    due: "Aug 18, 2026",
    status: "Sent",
  },
  {
    id: "inv-2301",
    number: "INV-2301",
    companyId: "c-bellweather",
    companyName: "Bellweather Logistics",
    amount: 15600,
    terms: "Net 15",
    due: "Sep 1, 2026",
    status: "Sent",
  },
  {
    id: "inv-2265",
    number: "INV-2265",
    companyId: "c-cascade",
    companyName: "Cascade Ventures",
    amount: 6900,
    terms: "Net 30",
    due: "Jul 20, 2026",
    status: "Paid",
  },
  {
    id: "inv-2288",
    number: "INV-2288",
    companyId: "c-oakton",
    companyName: "Oakton Technologies",
    amount: 11200,
    terms: "Net 30",
    due: "Jul 29, 2026",
    status: "Overdue",
  },
];

export const companyActivities: Record<string, ActivityItem[]> = {
  "c-cascade": [
    { id: "a1", when: "Today, 9:12 AM", text: "M. Doyle logged 2.5h on Q3 Warehouse Rollout." },
    { id: "a2", when: "Yesterday, 4:40 PM", text: "Client approved Milestone: Site Survey Complete." },
    { id: "a3", when: "Aug 3, 2026", text: "Invoice INV-2291 sent ($12,400)." },
    { id: "a4", when: "Aug 1, 2026", text: "New ticket raised: Portal login issue." },
  ],
};

export const billingTotals = {
  outstanding: 84220,
  overdue: 12400,
  inTerms: 71820,
  paidMtd: 56900,
};

export const profitability = {
  revenueRecognized: 412900,
  actualCost: 268400,
  grossMargin: 35,
  avgUtilization: 78,
  revenueDelta: "+8.2% vs Q2",
  costDelta: "+3.1% vs Q2",
  marginDelta: "+2 pts",
  utilDelta: "-1 pt",
  topAccounts: [
    { name: "Cascade Ventures", amount: 96200 },
    { name: "Bellweather Logistics", amount: 71050 },
    { name: "Northridge Retail Group", amount: 58900 },
  ],
};

export function money(n: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(n);
}

export function assertNoEmDash(value: string) {
  if (value.includes("\u2014") || value.includes("\u2013")) {
    throw new Error(`Forbidden dash character in copy: ${value}`);
  }
  return value;
}
