import type {
  Benefit,
  CrossDependency,
  GovernanceGate,
  Idea,
  IssueItem,
  Portfolio,
  Program,
  ResourceAllocation,
  RiskItem,
  StrategicObjective,
} from "./types";

export const seedObjectives: StrategicObjective[] = [
  {
    id: "so-ops",
    code: "SO-1",
    name: "Modernize client operations",
    owner: "M. Doyle",
    horizon: "2026 H2",
    status: "On Track",
    target: "3 go-lives with on-time delivery",
    progress: 68,
    description: "Warehouse, vendor, and logistics programs that raise client operating reliability.",
  },
  {
    id: "so-rev",
    code: "SO-2",
    name: "Protect delivery margin",
    owner: "J. Alvarez",
    horizon: "FY 2026",
    status: "At Risk",
    target: "Blended margin at or above 28%",
    progress: 54,
    description: "Keep utilization, leakage, and write-offs inside the boutique recovery band.",
  },
  {
    id: "so-exp",
    code: "SO-3",
    name: "Raise digital experience quality",
    owner: "S. Cho",
    horizon: "2026 Q4",
    status: "Lagging",
    target: "2 client digital products in production",
    progress: 35,
    description: "Marketing, portal, and POS work that clients can see and use.",
  },
  {
    id: "so-gov",
    code: "SO-4",
    name: "Institutionalize PMO governance",
    owner: "Dillon Morgan",
    horizon: "2026 Q4",
    status: "On Track",
    target: "Stage gates on every active project",
    progress: 72,
    description: "Standard intake, scoring, and signoff so leadership can see risk early.",
  },
];

export const seedIdeas: Idea[] = [
  {
    id: "idea-1",
    name: "Warehouse robotics assessment",
    companyId: "c-cascade",
    companyName: "Cascade Ventures",
    submitter: "Dana Kessler",
    stage: "Scoring",
    score: 78,
    strategicFit: 9,
    valueScore: 8,
    riskScore: 4,
    objectiveId: "so-ops",
    requestedBudget: 42000,
    summary: "Feasibility study for pick-assist robots after the WMS go-live.",
  },
  {
    id: "idea-2",
    name: "Client portal analytics pack",
    submitter: "M. Doyle",
    stage: "Approved",
    score: 71,
    strategicFit: 8,
    valueScore: 7,
    riskScore: 3,
    objectiveId: "so-gov",
    requestedBudget: 18000,
    summary: "Shared status, SLA, and invoice pack for every portal tenant.",
  },
  {
    id: "idea-3",
    name: "Legal knowledge base",
    companyId: "c-harlow",
    companyName: "Harlow & Pine Law",
    submitter: "J. Alvarez",
    stage: "Submitted",
    score: 44,
    strategicFit: 4,
    valueScore: 5,
    riskScore: 6,
    objectiveId: "so-exp",
    requestedBudget: 26000,
    summary: "Matter templates and search for a prospect account. Hold until the sale advances.",
  },
];

export const seedPortfolios: Portfolio[] = [
  {
    id: "pf-delivery",
    name: "Client Delivery 2026",
    owner: "M. Doyle",
    theme: "External value",
    budget: 388000,
    projectIds: ["p-warehouse", "p-website", "p-vendor", "p-fleet", "p-pos"],
    objectiveIds: ["so-ops", "so-rev", "so-exp"],
    description: "All billable client work currently in flight. This is the investment book leadership reviews weekly.",
  },
  {
    id: "pf-enable",
    name: "Firm Enablement",
    owner: "Dillon Morgan",
    theme: "Internal capability",
    budget: 18000,
    projectIds: [],
    objectiveIds: ["so-gov"],
    description: "Internal PMO, automation, and portal quality work. Ideas land here before they become projects.",
  },
];

export const seedPrograms: Program[] = [
  {
    id: "pg-cascade",
    name: "Cascade Operations Modernization",
    portfolioId: "pf-delivery",
    owner: "M. Doyle",
    status: "At Risk",
    projectIds: ["p-warehouse", "p-vendor", "p-website"],
    objectiveId: "so-ops",
    description: "One client program: warehouse go-live, vendor intake, and the public site that explains the change.",
  },
  {
    id: "pg-commerce",
    name: "Commerce and Logistics",
    portfolioId: "pf-delivery",
    owner: "S. Cho",
    status: "Overdue",
    projectIds: ["p-fleet", "p-pos"],
    objectiveId: "so-exp",
    description: "Retail POS sync and fleet tracking. Shared integration patterns, separate companies.",
  },
];

export const seedRisks: RiskItem[] = [
  {
    id: "rk-1",
    title: "Homepage review may slip cutover",
    projectId: "p-website",
    programId: "pg-cascade",
    owner: "J. Kim",
    probability: "High",
    impact: "High",
    status: "Mitigating",
    due: "2026-08-12",
    mitigation: "Lock content freeze and add a fallback homepage if CMS migration slips.",
  },
  {
    id: "rk-2",
    title: "Fleet GPS vendor latency",
    projectId: "p-fleet",
    programId: "pg-commerce",
    owner: "S. Cho",
    probability: "Medium",
    impact: "Critical",
    status: "Open",
    due: "2026-08-09",
    mitigation: "Pilot a second carrier and document SLA credits.",
  },
  {
    id: "rk-3",
    title: "Margin compression on website work",
    projectId: "p-website",
    owner: "J. Alvarez",
    probability: "Medium",
    impact: "High",
    status: "Open",
    due: "2026-08-15",
    mitigation: "Cap change requests and move extra photography to a paid change order.",
  },
  {
    id: "rk-4",
    title: "Portal SSO mapping after password reset",
    projectId: "p-warehouse",
    owner: "J. Kim",
    probability: "Low",
    impact: "Medium",
    status: "Mitigating",
    due: "2026-08-08",
    mitigation: "Ticket 1042 is in progress. Confirm both Cascade contacts can sign in.",
  },
];

export const seedIssues: IssueItem[] = [
  {
    id: "is-1",
    title: "Two Cascade contacts cannot open the portal",
    projectId: "p-warehouse",
    owner: "J. Kim",
    severity: "High",
    status: "In Progress",
    raised: "2026-08-05",
  },
  {
    id: "is-2",
    title: "Invoice PDF missing line items for Oakton",
    projectId: "p-pos",
    owner: "J. Alvarez",
    severity: "Medium",
    status: "Open",
    raised: "2026-08-04",
  },
];

export const seedDependencies: CrossDependency[] = [
  {
    id: "dep-1",
    predecessorProjectId: "p-warehouse",
    successorProjectId: "p-website",
    type: "Data",
    status: "At Risk",
    note: "Site launch copy depends on confirmed go-live dates from warehouse hypercare.",
  },
  {
    id: "dep-2",
    predecessorProjectId: "p-vendor",
    successorProjectId: "p-warehouse",
    type: "Finish to Start",
    status: "On Track",
    note: "Vendor intake must be live before Zone B suppliers ship racking extras.",
  },
  {
    id: "dep-3",
    predecessorProjectId: "p-pos",
    successorProjectId: "p-fleet",
    type: "Shared Resource",
    status: "Blocked",
    note: "S. Cho is allocated above 100% across POS and fleet this week.",
  },
];

export const seedBenefits: Benefit[] = [
  {
    id: "bn-1",
    name: "Warehouse pick accuracy",
    objectiveId: "so-ops",
    projectId: "p-warehouse",
    metric: "Pick accuracy",
    baseline: "91%",
    target: "98%",
    current: "94%",
    progress: 43,
    owner: "M. Doyle",
  },
  {
    id: "bn-2",
    name: "Vendor onboarding cycle time",
    objectiveId: "so-ops",
    projectId: "p-vendor",
    metric: "Days to first PO",
    baseline: "21 days",
    target: "8 days",
    current: "11 days",
    progress: 77,
    owner: "S. Cho",
  },
  {
    id: "bn-3",
    name: "Delivery margin recovery",
    objectiveId: "so-rev",
    metric: "Blended margin",
    baseline: "22%",
    target: "28%",
    current: "26%",
    progress: 67,
    owner: "J. Alvarez",
  },
  {
    id: "bn-4",
    name: "Retail inventory freshness",
    objectiveId: "so-exp",
    projectId: "p-pos",
    metric: "Hours to POS sync",
    baseline: "18h",
    target: "2h",
    current: "6h",
    progress: 75,
    owner: "J. Alvarez",
  },
];

export const seedGates: GovernanceGate[] = [
  {
    id: "gt-1",
    name: "Warehouse go-live gate",
    projectId: "p-warehouse",
    stage: "Execute to Transition",
    owner: "M. Doyle",
    due: "2026-08-18",
    status: "Upcoming",
    criteria: "Training complete, WMS roles signed off, hypercare roster named.",
  },
  {
    id: "gt-2",
    name: "Website design gate",
    projectId: "p-website",
    stage: "Design to Build",
    owner: "S. Cho",
    due: "2026-08-09",
    status: "In Review",
    criteria: "Homepage approved, content freeze confirmed, no open critical defects.",
  },
  {
    id: "gt-3",
    name: "Fleet pilot continue/stop",
    projectId: "p-fleet",
    stage: "Pilot to Scale",
    owner: "Dillon Morgan",
    due: "2026-08-10",
    status: "In Review",
    criteria: "Latency under 4s, 12 trucks reporting, commercial case still above 18% margin.",
  },
  {
    id: "gt-4",
    name: "Vendor closeout",
    projectId: "p-vendor",
    stage: "Close",
    owner: "S. Cho",
    due: "2026-08-12",
    status: "Upcoming",
    criteria: "Final signoff, leftover hours allocated or written off.",
  },
];

export const seedAllocations: ResourceAllocation[] = [
  { id: "al-1", memberId: "tm-md", memberName: "M. Doyle", projectId: "p-warehouse", projectName: "Q3 Warehouse Rollout", allocationPct: 50, hoursPerWeek: 20, start: "2026-07-01", end: "2026-08-22" },
  { id: "al-2", memberId: "tm-md", memberName: "M. Doyle", projectId: "p-website", projectName: "Website Replatform", allocationPct: 30, hoursPerWeek: 12, start: "2026-07-15", end: "2026-09-10" },
  { id: "al-3", memberId: "tm-jk", memberName: "J. Kim", projectId: "p-warehouse", projectName: "Q3 Warehouse Rollout", allocationPct: 40, hoursPerWeek: 16, start: "2026-07-20", end: "2026-08-22" },
  { id: "al-4", memberId: "tm-jk", memberName: "J. Kim", projectId: "p-website", projectName: "Website Replatform", allocationPct: 45, hoursPerWeek: 18, start: "2026-08-01", end: "2026-09-10" },
  { id: "al-5", memberId: "tm-sc", memberName: "S. Cho", projectId: "p-vendor", projectName: "Vendor Onboarding Portal", allocationPct: 35, hoursPerWeek: 14, start: "2026-06-20", end: "2026-08-12" },
  { id: "al-6", memberId: "tm-sc", memberName: "S. Cho", projectId: "p-fleet", projectName: "Fleet Tracking Pilot", allocationPct: 55, hoursPerWeek: 22, start: "2026-06-01", end: "2026-08-30" },
  { id: "al-7", memberId: "tm-sc", memberName: "S. Cho", projectId: "p-pos", projectName: "POS Integration", allocationPct: 25, hoursPerWeek: 10, start: "2026-07-10", end: "2026-08-28" },
  { id: "al-8", memberId: "tm-sa", memberName: "S. Ahmed", projectId: "p-warehouse", projectName: "Q3 Warehouse Rollout", allocationPct: 60, hoursPerWeek: 24, start: "2026-08-01", end: "2026-08-22" },
  { id: "al-9", memberId: "tm-ja", memberName: "J. Alvarez", projectId: "p-pos", projectName: "POS Integration", allocationPct: 20, hoursPerWeek: 8, start: "2026-07-10", end: "2026-08-28" },
];
